modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"
[[mods]]
modId = "moonstone"
version = "1.3.0.5-neoforge"
displayName = "Moonstone"
authors = "Ytgld"
description = '''.'''

[[mixins]]
config = "moonstone.mixins.json"

[[dependencies.moonstone]]
modId="neoforge"
type="required"
versionRange="[21.0.28-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.moonstone]]
modId="curios"
type="required"
versionRange="[9.4.0+1.21.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.moonstone]]
modId="minecraft"
type="required"
versionRange="[1.21, 1.22)"
ordering="NONE"
side="BOTH"